# Site settings
email: okay@samesies.io
baseurl: ""
google_analytics: 

name: Thomas Vaeth
title: Samesies
description: >
  Thomas Vaeth is a Software Engineer at Getty Images in Seattle, Washington.
url: "http://samesies.io"
twitter_username: thomasvaeth
default_img: https://source.unsplash.com/oBb-Y26PJgg/1600x900

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - octopress-autoprefixer
sass:
  style: compressed
exclude:
  - node_modules
  - .DS_Store
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json

# Collections
collections:
  themes:
    output: true
    permalink: "/themes/:path"
  documentation:
    output: true
    permalink: "/documentation/:path"
