# Site settings
email: thomas.vaeth@gmail.com
baseurl: ""
paginate: 999
paginate_path: "/blog/page-:num"
google_analytics: 

name: Thomas Vaeth
title: Samesies
description: >
  Thomas Vaeth is a Software Engineer at Getty Images in Seattle, Washington.
url: http://samesies.io
twitter_username: thomasvaeth
default_img: 

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
