# Site settings
email: thomas.vaeth@gmail.com
baseurl: ""
google_analytics: 

name: Thomas Vaeth
title: Samesies
description: >
  Thomas Vaeth is a Software Engineer at Getty Images in Seattle, Washington.
url: "http://samesies.io"
twitter_username: thomasvaeth
default_img: 

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  compress:
    css: sass
    js: uglifier
  sources:
    - _assets/css
    - _assets/images
    - _assets/js
exclude:
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  themes:
    output: true
    permalink: "/themes/:path"
  documentation:
    output: true
    permalink: "/documentation/:path"
